[cicd] Add check on mandatory files

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -678,16 +678,34 @@ requirements:
       echo "NO README.md found"; 
       exit 1; 
     fi
-    if [[ -f installer ]]; then 
-      echo "installer found"; 
-      if [[ -x installer ]]; then 
-        echo "installer executable"; 
+    if [[ -d docs ]]; then 
+      echo "docs directory found"; 
+    else 
+      echo "NO docs directory found"; 
+      exit 1; 
+    fi
+    if [[ -f podman-helper.sh ]]; then 
+      echo "podman-helper.sh found"; 
+      if [[ -x podman-helper.sh ]]; then 
+        echo "podman-helper.sh executable"; 
       else 
-        echo "Could not execute installer"; 
+        echo "Could not execute podman-helper.sh"; 
         exit 1; 
       fi
     else 
-      echo "NO installer found"; 
+      echo "NO podman-helper.sh found"; 
+      exit 1; 
+    fi
+    if [[ -f okd-helper.sh ]]; then 
+      echo "okd-helper.sh found"; 
+      if [[ -x okd-helper.sh ]]; then 
+        echo "okd-helper.sh executable"; 
+      else 
+        echo "Could not execute okd-helper.sh"; 
+        exit 1; 
+      fi
+    else 
+      echo "NO okd-helper.sh found"; 
       exit 1; 
     fi
   only:
