[cicd] Test context check for pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,41 +1,41 @@
 
-# Stagging for this pipeline
-stages:
-  - "build"
+# # Stagging for this pipeline
+# stages:
+#   - "build"
 
 
-docker-build:
-  # Use the official docker image.
-  image: docker:latest
-  stage: build
-  services:
-    - docker:dind
-  before_script:
-    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
-  # Default branch leaves tag empty (= latest tag)
-  # All other branches are tagged with the escaped branch name (commit ref slug)
-  script:
-    - |
-      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
-        tag=""
-        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
-      else
-        tag=":$CI_COMMIT_REF_SLUG"
-        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
-      fi
-    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
-    - docker images
-    - "./travis/prepare-begin      fedora                   latest         rawhide"
-    - "./travis/prepare-docker     fedora                   latest         rawhide"
-    - "./travis/prepare-dockerhub  fedora                   latest         rawhide"
-    - "./travis/prepare-cache      fedora                   latest         rawhide"
-    - "./travis/prepare-end        fedora                   latest         rawhide"
-    # - docker push "$CI_REGISTRY_IMAGE${tag}"
-  # Run this job in a branch where a Dockerfile exists
-  rules:
-    - if: $CI_COMMIT_BRANCH
-      exists:
-        - Dockerfile
+# docker-build:
+#   # Use the official docker image.
+#   image: docker:latest
+#   stage: build
+#   services:
+#     - docker:dind
+#   before_script:
+#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
+#   # Default branch leaves tag empty (= latest tag)
+#   # All other branches are tagged with the escaped branch name (commit ref slug)
+#   script:
+#     - |
+#       if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
+#         tag=""
+#         echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
+#       else
+#         tag=":$CI_COMMIT_REF_SLUG"
+#         echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
+#       fi
+#     - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
+#     - docker images
+#     - "./travis/prepare-begin      fedora                   latest         rawhide"
+#     - "./travis/prepare-docker     fedora                   latest         rawhide"
+#     - "./travis/prepare-dockerhub  fedora                   latest         rawhide"
+#     - "./travis/prepare-cache      fedora                   latest         rawhide"
+#     - "./travis/prepare-end        fedora                   latest         rawhide"
+#     # - docker push "$CI_REGISTRY_IMAGE${tag}"
+#   # Run this job in a branch where a Dockerfile exists
+#   rules:
+#     - if: $CI_COMMIT_BRANCH
+#       exists:
+#         - Dockerfile
 
 
 
@@ -420,4 +420,309 @@ docker-build:
 #     fi
 #   only:
 #     - stable
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+#######################################################
+
+# This is the GitLab CI/CD configuration file for sxcm kubernetes cluster manager.
+#
+# For more information, see: https://sxcm.readthedocs.io
+
+# Global environment variables
+variables:
+  SXGLCI_GIT_DOMAIN: gitlab.com
+  SXGLCI_GIT_SSH_USER: git@gitlab.com
+  SX_VERBOSE: "true"
+  SX_DEBUG: "true"
+
+# Default container image
+image: "quay.io/startx/runner-bash:alpine3"
+
+# Include library
+include:
+  - template: Security/SAST.gitlab-ci.yml
+
+# Stagging for this pipeline
+stages:
+  - "context check"
+  - "syntax check"
+  - "test"
+  - "build"
+
+##
+## LIBRARY
+##
+
+# Library used to merge branch in a local repo
+.build-image:
+  variables:
+    SXGLCI_BRANCH_FROM: 'devel' # default to devel branch
+    SXGLCI_BRANCH_TO: 'main' # default to main branch
+  before_script: 
+    - |
+      #!/bin/bash
+      echo "======== Configuration of git repository"
+      if [[ $SX_DEBUG == true ]]; then
+        git config user.email "devops@startx.fr"
+        git config user.name "STARTX Gitlab-CI"
+        git config fetch.recurseSubmodules true
+        git config advice.detachedHead false
+      else
+        git config user.email "devops@startx.fr" &> /dev/null
+        git config user.name "STARTX Gitlab-CI" &> /dev/null
+        git config fetch.recurseSubmodules true &> /dev/null
+        git config advice.detachedHead false &> /dev/null
+      fi
+      echo "======== Configuration of SSH key"
+      if [[ $SX_DEBUG == true ]]; then
+        eval $(ssh-agent -s)
+        mkdir -p ~/.ssh && chmod 740 ~/.ssh
+        echo $SXGLCI_GITSSH_PRIVB64 | base64 -d > ~/.ssh/sxcm-gitlabci.id_ecdsa
+        chmod 600 ~/.ssh/sxcm-gitlabci.id_ecdsa
+        ssh-add ~/.ssh/sxcm-gitlabci.id_ecdsa
+        $(ssh-keyscan $SXGLCI_GIT_DOMAIN >> ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts)
+      else
+        eval $(ssh-agent -s) &> /dev/null
+        mkdir -p ~/.ssh && chmod 740 ~/.ssh
+        echo $SXGLCI_GITSSH_PRIVB64 | base64 -d > ~/.ssh/sxcm-gitlabci.id_ecdsa
+        chmod 600 ~/.ssh/sxcm-gitlabci.id_ecdsa
+        ssh-add ~/.ssh/sxcm-gitlabci.id_ecdsa &> /dev/null
+        $(ssh-keyscan $SXGLCI_GIT_DOMAIN >> ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts)
+      fi
+      echo "======== Configuration of remote push to ${SXGLCI_GIT_SSH_USER}:${CI_PROJECT_PATH}.git"
+      if [[ $SX_DEBUG == true ]]; then
+        git remote set-url origin ${SXGLCI_GIT_SSH_USER}:${CI_PROJECT_PATH}.git
+        git fetch origin
+      else
+        git remote set-url origin ${SXGLCI_GIT_SSH_USER}:${CI_PROJECT_PATH}.git
+        git fetch origin &> /dev/null
+      fi
+  script: |
+    #!/bin/bash
+    echo "======== Checkout branch $SXGLCI_BRANCH_FROM"
+    if [[ $SX_DEBUG == true ]]; then
+      git checkout $SXGLCI_BRANCH_FROM
+    else
+      git checkout $SXGLCI_BRANCH_FROM &> /dev/null
+    fi
+    if [[ $? != 0 ]]; then
+      echo "!! Could not find origin branch $SXGLCI_BRANCH_FROM" && exit 1
+    fi
+    echo "======== Checkout branch $SXGLCI_BRANCH_TO"
+    if [[ $SX_DEBUG == true ]]; then
+      git checkout --track origin/$SXGLCI_BRANCH_TO && \
+      git checkout $SXGLCI_BRANCH_TO && \
+      git pull
+    else
+      git checkout --track origin/$SXGLCI_BRANCH_TO &> /dev/null && \
+      git checkout $SXGLCI_BRANCH_TO &> /dev/null && \
+      git pull &> /dev/null
+    fi
+    if [[ $? != 0 ]]; then
+      echo "!! Could not find destination branch $SXGLCI_BRANCH_TO" && exit 1
+    fi
+    echo "======== Merge branch $SXGLCI_BRANCH_FROM into $SXGLCI_BRANCH_TO"
+    if [[ $SX_DEBUG == true ]]; then
+      git merge --no-ff $SXGLCI_BRANCH_FROM
+    else
+      git merge --no-ff $SXGLCI_BRANCH_FROM &> /dev/null
+    fi
+    if [[ $? != 0 ]]; then
+      echo "!! Could not automaticaly merge branch $SXGLCI_BRANCH_FROM into $SXGLCI_BRANCH_TO" && exit 1
+    fi
+    echo "======== Push branch $SXGLCI_BRANCH_TO into ${SXGLCI_GIT_SSH_USER}:${CI_PROJECT_PATH}.git"
+    if [[ $SX_DEBUG == true ]]; then
+      git push origin $SXGLCI_BRANCH_TO
+    else
+      git push origin $SXGLCI_BRANCH_TO &> /dev/null
+    fi
+    if [[ $? != 0 ]]; then
+      echo "!! Could not automaticaly push branch $SXGLCI_BRANCH_TO"
+      exit 1
+    fi
+
+##
+## STAGES
+##
+
+# Debug stage, used when developping the ci/cd chain
+debug:
+  stage: "context check"
+  script: |
+    #!/bin/bash
+    VS_PYTHON=$(python3 --version)
+    MDL_PYTHON=$(mdl --version)
+    SS_PYTHON=$(shellcheck --version)
+    DDSIZE=$(du -sh .)
+    if [[ $SX_DEBUG == true ]]; then
+    cat <<EOF
+    ======== DEBUG
+    python version     : $VS_PYTHON
+    mdl version        : $MDL_PYTHON
+    shellcheck version : $SS_PYTHON
+    directory size     : $DDSIZE
+    EOF
+    else
+    cat <<EOF
+    ======== DEBUG
+    python version     : $VS_PYTHON
+    directory size     : $DDSIZE
+    EOF
+    fi
+  only:
+    - master
+
+# Info stage, used to get the execution context
+info:
+  stage: "context check"
+  image: "busybox:latest"
+  script: |
+    #!/bin/bash
+    if [[ $SX_DEBUG == true ]]; then
+    cat <<EOF
+    ======== USER INFO
+    ID         : $GITLAB_USER_ID
+    e-mail     : $GITLAB_USER_EMAIL
+    Username   : $GITLAB_USER_NAME
+    
+    ======== SERVER INFO
+    Hostname   : $HOSTNAME
+    Runner     : $CI_RUNNER_DESCRIPTION
+    Arch       : $CI_RUNNER_EXECUTABLE_ARCH
+    Version    : $CI_RUNNER_VERSION ($CI_SERVER_REVISION)
+    Image      : $CI_JOB_IMAGE
+    
+    ======== PROJECT INFO
+    Namespace  : $CI_PROJECT_ROOT_NAMESPACE
+    Name       : $CI_PROJECT_TITLE
+    Path       : $CI_PROJECT_PATH ($CI_PROJECT_VISIBILITY)
+    URL        : $CI_PROJECT_URL
+    Language   : $CI_PROJECT_REPOSITORY_LANGUAGES
+    Labels     : $CI_PROJECT_CLASSIFICATION_LABEL
+    
+    ======== JOB INFO
+    ID         : $CI_JOB_NAME ($CI_JOB_ID)
+    Started    : $CI_JOB_STARTED_AT
+    Pipeline   : $CI_PIPELINE_ID ($CI_PIPELINE_CREATED_AT)
+    URL        : $CI_PIPELINE_URL
+    Language   : $CI_PROJECT_REPOSITORY_LANGUAGES
+    Labels     : $CI_PROJECT_CLASSIFICATION_LABEL
+    
+    ======== COMMIT INFO
+    Previous   : $CI_COMMIT_BEFORE_SHA
+    Current    : $CI_COMMIT_SHA
+    Date       : $CI_COMMIT_TIMESTAMP
+    Branch     : $CI_COMMIT_BRANCH
+    Autor      : $CI_COMMIT_AUTHOR
+    Title      : $CI_COMMIT_TITLE
+    EOF
+    else
+    cat <<EOF
+    User info  : $GITLAB_USER_ID ($GITLAB_USER_EMAIL)
+    Runner     : $HOSTNAME ($CI_RUNNER_EXECUTABLE_ARCH : CI_RUNNER_VERSION ($CI_SERVER_REVISION))
+    Image      : $CI_JOB_IMAGE
+    Project    : $CI_PROJECT_ROOT_NAMESPACE ($CI_PROJECT_PATH ($CI_PROJECT_VISIBILITY))
+    Job ID     : $CI_JOB_NAME ($CI_JOB_ID) - started at $CI_JOB_STARTED_AT
+    Pipeline   : $CI_PIPELINE_ID ($CI_PIPELINE_CREATED_AT)
+    Commit     : $CI_COMMIT_SHA - at $CI_COMMIT_TIMESTAMP
+    Branch     : $CI_COMMIT_BRANCH
+    Autor      : $CI_COMMIT_AUTHOR
+    Title      : $CI_COMMIT_TITLE
+    EOF
+    fi
+  only:
+    - master
+
+# Check stage, used to check for good context
+requirements:
+  stage: "context check"
+  image: "busybox:latest"
+  script: |
+    #!/bin/bash
+    if [[ -f LICENSE ]]; then 
+      echo "LICENSE found"; 
+    else 
+      echo "NO LICENSE found"; 
+      exit 1; 
+    fi
+    if [[ -f README.md ]]; then 
+      echo "README.md found"; 
+    else 
+      echo "NO README.md found"; 
+      exit 1; 
+    fi
+    if [[ -f installer ]]; then 
+      echo "installer found"; 
+      if [[ -x installer ]]; then 
+        echo "installer executable"; 
+      else 
+        echo "Could not execute installer"; 
+        exit 1; 
+      fi
+    else 
+      echo "NO installer found"; 
+      exit 1; 
+    fi
+  only:
+    - master
+
+# First stage; all branches
+markdown:
+  stage: "syntax check"
+  script: |
+    #!/bin/bash
+    mdl --skip-default-ruleset *.md
+  only:
+    - master
+shell:
+  stage: "syntax check"
+  script: "shellcheck installer"
+  only:
+    - master
+
+# #Second stage; only dev branch
+# bats:
+#   stage: "test"
+#   script: "cd tests && ./start.sh"
+#   only:
+#     - master
+
+## Build image
+
+# Build the fedora 
+build-fedora:
+  stage: "build"
+  extends: .build-image
+  variables:
+    SXGLCI_BRANCH_FROM: 'devel'
+    SXGLCI_BRANCH_TO: 'main'
+  only:
+    - master
 
