[latest] Disable fatal in travis build and improve finish display

diff --git a/travis/finish-end b/travis/finish-end
--- a/travis/finish-end
+++ b/travis/finish-end
@@ -5,5 +5,13 @@ if [ "$1" = true ] ; then
     echo 0
 else
     echo "--------> Build was partially performed"
-    echo 2;
+    echo "!!!!!!!!> An error happened in your build"
+    if [ "$SX_DEBUG" = true ] ; then
+        echo $TRAVIS_TEST_RESULT
+    fi
+    if [[ "$ISFATAL" = "true" ]]; then
+        exit 2;
+    else
+        exit 0;
+    fi
 fi
